USE DSPARTYMANAGEMENT;

ALTER TABLE ORGANIZATION DROP FOREIGN KEY FK_ORGANIZATION_CHARACTERISTIC_ORGANIZATION__0;

ALTER TABLE ORGANIZATION DROP COLUMN CHARACTERISTIC_ORGANIZATION__0;

ALTER TABLE CHARACTERISTIC ADD CHARACTERISTIC_ORGANIZATION_ID varchar(255) DEFAULT NULL;
ALTER TABLE CHARACTERISTIC ADD CONSTRAINT FK_CHARACTERISTIC_CHARACTERISTIC_ORGANIZATION_ID FOREIGN KEY (CHARACTERISTIC_ORGANIZATION_ID) REFERENCES ORGANIZATION(ID);
